# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/descombes/libnavajo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/descombes/libnavajo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"headers\" \"libraries\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/descombes/libnavajo/CMakeFiles /home/descombes/libnavajo/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/descombes/libnavajo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f CMakeFiles/doc.dir/build.make CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named navajo

# Build rule for target.
navajo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 navajo
.PHONY : navajo

# fast build rule for target.
navajo/fast:
	$(MAKE) -f CMakeFiles/navajo.dir/build.make CMakeFiles/navajo.dir/build
.PHONY : navajo/fast

#=============================================================================
# Target rules for targets named navajoPrecompiler

# Build rule for target.
navajoPrecompiler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 navajoPrecompiler
.PHONY : navajoPrecompiler

# fast build rule for target.
navajoPrecompiler/fast:
	$(MAKE) -f CMakeFiles/navajoPrecompiler.dir/build.make CMakeFiles/navajoPrecompiler.dir/build
.PHONY : navajoPrecompiler/fast

src/AuthPAM.o: src/AuthPAM.cc.o
.PHONY : src/AuthPAM.o

# target to build an object file
src/AuthPAM.cc.o:
	$(MAKE) -f CMakeFiles/navajo.dir/build.make CMakeFiles/navajo.dir/src/AuthPAM.cc.o
.PHONY : src/AuthPAM.cc.o

src/AuthPAM.i: src/AuthPAM.cc.i
.PHONY : src/AuthPAM.i

# target to preprocess a source file
src/AuthPAM.cc.i:
	$(MAKE) -f CMakeFiles/navajo.dir/build.make CMakeFiles/navajo.dir/src/AuthPAM.cc.i
.PHONY : src/AuthPAM.cc.i

src/AuthPAM.s: src/AuthPAM.cc.s
.PHONY : src/AuthPAM.s

# target to generate assembly for a file
src/AuthPAM.cc.s:
	$(MAKE) -f CMakeFiles/navajo.dir/build.make CMakeFiles/navajo.dir/src/AuthPAM.cc.s
.PHONY : src/AuthPAM.cc.s

src/LocalRepository.o: src/LocalRepository.cc.o
.PHONY : src/LocalRepository.o

# target to build an object file
src/LocalRepository.cc.o:
	$(MAKE) -f CMakeFiles/navajo.dir/build.make CMakeFiles/navajo.dir/src/LocalRepository.cc.o
.PHONY : src/LocalRepository.cc.o

src/LocalRepository.i: src/LocalRepository.cc.i
.PHONY : src/LocalRepository.i

# target to preprocess a source file
src/LocalRepository.cc.i:
	$(MAKE) -f CMakeFiles/navajo.dir/build.make CMakeFiles/navajo.dir/src/LocalRepository.cc.i
.PHONY : src/LocalRepository.cc.i

src/LocalRepository.s: src/LocalRepository.cc.s
.PHONY : src/LocalRepository.s

# target to generate assembly for a file
src/LocalRepository.cc.s:
	$(MAKE) -f CMakeFiles/navajo.dir/build.make CMakeFiles/navajo.dir/src/LocalRepository.cc.s
.PHONY : src/LocalRepository.cc.s

src/LogFile.o: src/LogFile.cc.o
.PHONY : src/LogFile.o

# target to build an object file
src/LogFile.cc.o:
	$(MAKE) -f CMakeFiles/navajo.dir/build.make CMakeFiles/navajo.dir/src/LogFile.cc.o
.PHONY : src/LogFile.cc.o

src/LogFile.i: src/LogFile.cc.i
.PHONY : src/LogFile.i

# target to preprocess a source file
src/LogFile.cc.i:
	$(MAKE) -f CMakeFiles/navajo.dir/build.make CMakeFiles/navajo.dir/src/LogFile.cc.i
.PHONY : src/LogFile.cc.i

src/LogFile.s: src/LogFile.cc.s
.PHONY : src/LogFile.s

# target to generate assembly for a file
src/LogFile.cc.s:
	$(MAKE) -f CMakeFiles/navajo.dir/build.make CMakeFiles/navajo.dir/src/LogFile.cc.s
.PHONY : src/LogFile.cc.s

src/LogRecorder.o: src/LogRecorder.cc.o
.PHONY : src/LogRecorder.o

# target to build an object file
src/LogRecorder.cc.o:
	$(MAKE) -f CMakeFiles/navajo.dir/build.make CMakeFiles/navajo.dir/src/LogRecorder.cc.o
.PHONY : src/LogRecorder.cc.o

src/LogRecorder.i: src/LogRecorder.cc.i
.PHONY : src/LogRecorder.i

# target to preprocess a source file
src/LogRecorder.cc.i:
	$(MAKE) -f CMakeFiles/navajo.dir/build.make CMakeFiles/navajo.dir/src/LogRecorder.cc.i
.PHONY : src/LogRecorder.cc.i

src/LogRecorder.s: src/LogRecorder.cc.s
.PHONY : src/LogRecorder.s

# target to generate assembly for a file
src/LogRecorder.cc.s:
	$(MAKE) -f CMakeFiles/navajo.dir/build.make CMakeFiles/navajo.dir/src/LogRecorder.cc.s
.PHONY : src/LogRecorder.cc.s

src/LogStdOutput.o: src/LogStdOutput.cc.o
.PHONY : src/LogStdOutput.o

# target to build an object file
src/LogStdOutput.cc.o:
	$(MAKE) -f CMakeFiles/navajo.dir/build.make CMakeFiles/navajo.dir/src/LogStdOutput.cc.o
.PHONY : src/LogStdOutput.cc.o

src/LogStdOutput.i: src/LogStdOutput.cc.i
.PHONY : src/LogStdOutput.i

# target to preprocess a source file
src/LogStdOutput.cc.i:
	$(MAKE) -f CMakeFiles/navajo.dir/build.make CMakeFiles/navajo.dir/src/LogStdOutput.cc.i
.PHONY : src/LogStdOutput.cc.i

src/LogStdOutput.s: src/LogStdOutput.cc.s
.PHONY : src/LogStdOutput.s

# target to generate assembly for a file
src/LogStdOutput.cc.s:
	$(MAKE) -f CMakeFiles/navajo.dir/build.make CMakeFiles/navajo.dir/src/LogStdOutput.cc.s
.PHONY : src/LogStdOutput.cc.s

src/LogSyslog.o: src/LogSyslog.cc.o
.PHONY : src/LogSyslog.o

# target to build an object file
src/LogSyslog.cc.o:
	$(MAKE) -f CMakeFiles/navajo.dir/build.make CMakeFiles/navajo.dir/src/LogSyslog.cc.o
.PHONY : src/LogSyslog.cc.o

src/LogSyslog.i: src/LogSyslog.cc.i
.PHONY : src/LogSyslog.i

# target to preprocess a source file
src/LogSyslog.cc.i:
	$(MAKE) -f CMakeFiles/navajo.dir/build.make CMakeFiles/navajo.dir/src/LogSyslog.cc.i
.PHONY : src/LogSyslog.cc.i

src/LogSyslog.s: src/LogSyslog.cc.s
.PHONY : src/LogSyslog.s

# target to generate assembly for a file
src/LogSyslog.cc.s:
	$(MAKE) -f CMakeFiles/navajo.dir/build.make CMakeFiles/navajo.dir/src/LogSyslog.cc.s
.PHONY : src/LogSyslog.cc.s

src/WebServer.o: src/WebServer.cc.o
.PHONY : src/WebServer.o

# target to build an object file
src/WebServer.cc.o:
	$(MAKE) -f CMakeFiles/navajo.dir/build.make CMakeFiles/navajo.dir/src/WebServer.cc.o
.PHONY : src/WebServer.cc.o

src/WebServer.i: src/WebServer.cc.i
.PHONY : src/WebServer.i

# target to preprocess a source file
src/WebServer.cc.i:
	$(MAKE) -f CMakeFiles/navajo.dir/build.make CMakeFiles/navajo.dir/src/WebServer.cc.i
.PHONY : src/WebServer.cc.i

src/WebServer.s: src/WebServer.cc.s
.PHONY : src/WebServer.s

# target to generate assembly for a file
src/WebServer.cc.s:
	$(MAKE) -f CMakeFiles/navajo.dir/build.make CMakeFiles/navajo.dir/src/WebServer.cc.s
.PHONY : src/WebServer.cc.s

src/navajoPrecompiler.o: src/navajoPrecompiler.cc.o
.PHONY : src/navajoPrecompiler.o

# target to build an object file
src/navajoPrecompiler.cc.o:
	$(MAKE) -f CMakeFiles/navajoPrecompiler.dir/build.make CMakeFiles/navajoPrecompiler.dir/src/navajoPrecompiler.cc.o
.PHONY : src/navajoPrecompiler.cc.o

src/navajoPrecompiler.i: src/navajoPrecompiler.cc.i
.PHONY : src/navajoPrecompiler.i

# target to preprocess a source file
src/navajoPrecompiler.cc.i:
	$(MAKE) -f CMakeFiles/navajoPrecompiler.dir/build.make CMakeFiles/navajoPrecompiler.dir/src/navajoPrecompiler.cc.i
.PHONY : src/navajoPrecompiler.cc.i

src/navajoPrecompiler.s: src/navajoPrecompiler.cc.s
.PHONY : src/navajoPrecompiler.s

# target to generate assembly for a file
src/navajoPrecompiler.cc.s:
	$(MAKE) -f CMakeFiles/navajoPrecompiler.dir/build.make CMakeFiles/navajoPrecompiler.dir/src/navajoPrecompiler.cc.s
.PHONY : src/navajoPrecompiler.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... doc"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... navajo"
	@echo "... navajoPrecompiler"
	@echo "... rebuild_cache"
	@echo "... src/AuthPAM.o"
	@echo "... src/AuthPAM.i"
	@echo "... src/AuthPAM.s"
	@echo "... src/LocalRepository.o"
	@echo "... src/LocalRepository.i"
	@echo "... src/LocalRepository.s"
	@echo "... src/LogFile.o"
	@echo "... src/LogFile.i"
	@echo "... src/LogFile.s"
	@echo "... src/LogRecorder.o"
	@echo "... src/LogRecorder.i"
	@echo "... src/LogRecorder.s"
	@echo "... src/LogStdOutput.o"
	@echo "... src/LogStdOutput.i"
	@echo "... src/LogStdOutput.s"
	@echo "... src/LogSyslog.o"
	@echo "... src/LogSyslog.i"
	@echo "... src/LogSyslog.s"
	@echo "... src/WebServer.o"
	@echo "... src/WebServer.i"
	@echo "... src/WebServer.s"
	@echo "... src/navajoPrecompiler.o"
	@echo "... src/navajoPrecompiler.i"
	@echo "... src/navajoPrecompiler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

