#############################
# LIBNAVAJO EXAMPLES        #
# created by T.DESCOMBES    #
#                    2015   #
#############################

all:: 
	$(MAKE) -C 1_basic -f Makefile
	$(MAKE) -C 2_gauge -f Makefile
	$(MAKE) -C 3_websocket -f Makefile


clean::
	$(MAKE) -C 1_basic -f Makefile $@
	$(MAKE) -C 2_gauge -f Makefile $@
	$(MAKE) -C 3_websocket -f Makefile $@
	
